first round edit, let's give her a test

diff --git a/cloudflare-ddns-update b/cloudflare-ddns-update
--- a/cloudflare-ddns-update
+++ b/cloudflare-ddns-update
@@ -5,32 +5,59 @@
 # Needs the DNS record pre-creating on Cloudflare
 
 prgnam=cloudflare-ddns-update
-
 configfile=${configfile:-~/.local/etc/$prgnam.conf}
+configfile_secured=/tmp/${prgnam}_secured.conf
+
+# change this to preffered ip check source
+ipcheck=https://icanhazip.com
+
+set -e
+
+if [ ! -x $(which jq) ]; then
+    echo "Error: ${prgnam} requires 'jq' as a dependency"
+    echo "Try: 'sudo apt install jq' or 'sudo dnf install jq'"
+    exit 1
+fi
+
+clean_config() {
+    workingconfigfile=$1
+    if egrep -q -v '^#|^[^ ]*=[^;]*' "$workingconfigfile"; then
+        echo "Config file is unclean, cleaning it..." 
+        # filter the original to a new file
+        egrep '^#|^[^ ]*=[^;&]*'  "$workingconfigfile" > "$configfile_secured"
+        configfile="$configfile_secured"
+    fi
+}
 
 if [ -r $configfile ]; then
+    clean_config $configfile
     source $configfile
 elif [ -r /etc/$prgnam.conf ]; then
-    source /etc/$prgnam.conf
+    clean_config /etc/$prgnam.conf
+    source $configfile
 else
     echo "Error: cannot source config file."
     echo "Usage: configfile=/path/to/config ${prgnam}"
     exit 1
 fi
 
-
-
 # Get the current external IP address
-ip=$(curl -s -X GET https://checkip.amazonaws.com)
+ip=$(curl -s $ipcheck)
+exitstatus=$?
+if [ $exitstatus != 0 ]; then
+    echo "Error: could not get ip address from $ipcheck"
+    echo "Try changing the source with ipcheck=https://new-ip-check-here.example $prgnam"
+    exit 1
+fi
 
 echo "Current IP is $ip"
 
 if host $dnsrecord 1.1.1.1 | grep "has address" | grep "$ip"; then
   echo "$dnsrecord is currently set to $ip; no changes needed"
-  exit
+  exit 0
 fi
 
-# if here, the dns record needs updating
+# the dns record needs updating
 
 # get the zone id for the requested zone
 zoneid=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones?name=$zone&status=active" \
@@ -54,3 +81,8 @@ curl -s -X PUT "https://api.cloudflare.com/client/v4/zones/$zoneid/dns_records/$
   -H "X-Auth-Key: $cloudflare_auth_key" \
   -H "Content-Type: application/json" \
   --data "{\"type\":\"A\",\"name\":\"$dnsrecord\",\"content\":\"$ip\",\"ttl\":1,\"proxied\":false}" | jq
+
+# clean-up
+rm -rf $configfile_secured
+
+exit 0
